import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Suspense } from "react";

import { GeistMono } from "geist/font/mono";

import { Toaster } from "@/components/ui/sonner";

import { ThemeProvider } from "next-themes";

import Navbar from "@/components/navbar";
import QueryClientProviders from "@/providers/react-query";
import ErrorSearchParams from "@/components/error-searchparams";
import Footer from "@/components/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`antialiased ${inter.variable} ${GeistMono.variable}`}
    >
      <QueryClientProviders>
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <body>
            <Suspense>
              <Navbar />
            </Suspense>
            <main className="min-h-screen">{children}</main>
            <ErrorSearchParams />
            <Suspense>
              <Footer />
            </Suspense>
            <Toaster />
          </body>
        </ThemeProvider>
        <ReactQueryDevtools />
      </QueryClientProviders>
    </html>
  );
}
